server:
  port: 9000
spring:
  application:
    name: user
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: INFO