server:
  port: 9000
spring:
  application:
    name: user
  profiles:
    active: default
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: INFO