server:
  port: 9000
spring:
  application:
    name: user
  profiles:
    active: default
eureka:
  client:
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    # 定义服务失效时间，默认：90，单位：秒
    lease-expiration-duration-in-seconds: 90
    # 定义服务续约任务调用间隔时间，默认：30，单位：秒
    lease-renewal-interval-in-seconds: 30
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: INFO
